FROM python:3.7.10-slim-buster

RUN apt-get update && \
    apt-get install -y git curl && \
    apt-get upgrade -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install Pipenv
RUN pip3 install pipenv

# Install Poetry
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -

ENV PATH "/root/.poetry/bin:/root/.pyenv/bin:$PATH"

RUN curl -s https://api.github.com/repos/snyk/snyk/releases/latest | grep "browser_download_url" \
    | grep linux | cut -d '"' -f 4 | tr '\n' '\0' \
    | xargs -0 -n1 curl -s -L -O && sha256sum -c snyk-linux.sha256 && \
    mv snyk-linux /usr/local/bin/snyk && chmod +x /usr/local/bin/snyk

COPY entrypoints/ /usr/local/bin/entrypoints/
RUN chmod +x /usr/local/bin/entrypoints/*

COPY testrepo/ /root/testrepo

RUN rm -rf /tmp/*

ENTRYPOINT ["/usr/local/bin/entrypoints/python.sh"]