FROM maven:3.8.1-adoptopenjdk-15-openj9

RUN mkdir -p /usr/local/bin/

COPY scripts/install_snyk.sh /root/install_snyk.sh
RUN /bin/bash /root/install_snyk.sh

COPY entrypoints/ /usr/local/bin/entrypoints/
RUN chmod +x /usr/local/bin/entrypoints/*

COPY testrepo/ /root/testrepo

WORKDIR /root/testrepo

ENTRYPOINT ["/usr/local/bin/entrypoints/maven.sh"]
