FROM python:slim-buster

RUN apt-get update && \
    apt-get install -y git curl && \
    apt-get upgrade -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install Pipenv
RUN pip3 install pipenv

# Install Poetry
RUN curl -sSL https://install.python-poetry.org | python3 -

ENV PATH "/root/.poetry/bin:/root/.pyenv/bin:$PATH"

COPY scripts/install_snyk.sh /root/install_snyk.sh
RUN /bin/bash /root/install_snyk.sh

COPY entrypoints/ /usr/local/bin/entrypoints/
RUN chmod +x /usr/local/bin/entrypoints/*

COPY testrepo/ /root/testrepo

RUN rm -rf /tmp/*

WORKDIR /root/testrepo

ENTRYPOINT ["/usr/local/bin/entrypoints/python.sh"]