FROM node:lts-buster-slim

RUN apt-get update && \
    apt-get install -y curl jq && \
    apt-get upgrade -y && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /usr/local/bin/

COPY scripts/install_snyk.sh /root/install_snyk.sh
RUN /bin/bash /root/install_snyk.sh

RUN yarn set version 2

COPY entrypoints/ /usr/local/bin/entrypoints/
RUN chmod +x /usr/local/bin/entrypoints/*

COPY testrepo/ /root/testrepo

WORKDIR /root/testrepo

ENTRYPOINT ["/usr/local/bin/entrypoints/node.sh"]