FROM bitnami/dotnet:latest

# Install .NET
ENV DOTNET_VERSION=5.0.0

COPY scripts/install_snyk.sh /root/install_snyk.sh
RUN /bin/bash /root/install_snyk.sh

COPY entrypoints/ /usr/local/bin/entrypoints/
RUN chmod +x /usr/local/bin/entrypoints/*

COPY testrepo/ /root/testrepo

WORKDIR /root/testrepo

ENTRYPOINT ["/usr/local/bin/entrypoints/dotnet.sh"]
