FROM mrzarquon/pyenv:latest

ENV PATH "/root/.pyenv/bin:$PATH"

COPY --from=snyk/snyk:linux /usr/local/bin/snyk /usr/local/bin/snyk

COPY entrypoints/ /usr/local/bin/entrypoints/
RUN chmod +x /usr/local/bin/entrypoints/*

ENTRYPOINT ["/usr/local/bin/entrypoints/python.sh"]