FROM ruby:slim-buster

RUN apt-get update && \
    apt-get install -y curl && \
    apt-get install -y build-essential && \
    apt-get install -y gnupg2 && \
    apt-get upgrade -y && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /usr/local/bin/

# Install rvm
RUN curl -sSL https://rvm.io/mpapis.asc | gpg2 --import - && \
    curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import - && \
    curl -sSL https://get.rvm.io | bash -s stable

# Install Snyk
RUN curl -s https://api.github.com/repos/snyk/snyk/releases/latest | grep "browser_download_url" \
    | grep linux | cut -d '"' -f 4 | tr '\n' '\0' \
    | xargs -0 -n1 curl -s -L -O && sha256sum -c snyk-linux.sha256 && \
    mv snyk-linux /usr/local/bin/snyk && chmod +x /usr/local/bin/snyk

COPY entrypoints/ /usr/local/bin/entrypoints/
RUN chmod +x /usr/local/bin/entrypoints/*

COPY testrepo/ /root/testrepo

ENTRYPOINT ["/usr/local/bin/entrypoints/ruby.sh"]
