FROM python:slim-buster AS builder

RUN apt-get update && \
    apt-get install -y git make build-essential libssl-dev zlib1g-dev libbz2-dev \
    libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev \
    xz-utils tk-dev libffi-dev liblzma-dev && \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    curl -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash

ENV PATH "/root/.pyenv/bin:$PATH"
#ENV CONFIGURE_OPTS "--enable-optimizations"
RUN pyenv install 2.7.18
RUN pyenv install 3.5.10
RUN pyenv install 3.6.13
RUN pyenv install 3.7.10
RUN pyenv install 3.8.9
RUN pyenv install 3.9.4

FROM python:slim-buster

COPY --from=builder /root/.pyenv/ /root/.pyenv/

RUN rm -rf /tmp/*