FROM maven:3.8.1-adoptopenjdk-15-openj9

RUN mkdir -p /usr/local/bin/

RUN curl -s https://api.github.com/repos/snyk/snyk/releases/latest | grep "browser_download_url" \
    | grep linux | cut -d '"' -f 4 | tr '\n' '\0' \
    | xargs -0 -n1 curl -s -L -O && sha256sum -c snyk-linux.sha256 && \
    mv snyk-linux /usr/local/bin/snyk && chmod +x /usr/local/bin/snyk

COPY entrypoints/ /usr/local/bin/entrypoints/
RUN chmod +x /usr/local/bin/entrypoints/*

COPY testrepo/ /root/testrepo

ENTRYPOINT ["/usr/local/bin/entrypoints/maven.sh"]
