FROM node:lts-buster-slim

RUN apt-get update && \
    apt-get install -y git && \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY --from=snyk/snyk:linux /usr/local/bin/snyk /usr/local/bin/snyk

COPY entrypoints/ /usr/local/bin/entrypoints/
RUN chmod +x /usr/local/bin/entrypoints/*

ENTRYPOINT ["/usr/local/bin/entrypoints/javascript.sh"]