FROM golang:latest

RUN mkdir -p /usr/local/bin/

RUN mkdir /go/src/app

RUN curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

COPY scripts/install_snyk.sh /root/install_snyk.sh
RUN chmod +x /root/install_snyk.sh
RUN /root/install_snyk.sh

COPY entrypoints/ /usr/local/bin/entrypoints/
RUN chmod +x /usr/local/bin/entrypoints/*

COPY testrepo/ /go/src/testrepo

WORKDIR /go/src/testrepo

ENTRYPOINT ["/usr/local/bin/entrypoints/go.sh"]
