FROM golang:latest

RUN mkdir -p /usr/local/bin/

RUN mkdir /go/src/app

RUN curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

RUN curl -s https://api.github.com/repos/snyk/snyk/releases/latest | grep "browser_download_url" \
    | grep linux | cut -d '"' -f 4 | tr '\n' '\0' \
    | xargs -0 -n1 curl -s -L -O && sha256sum -c snyk-linux.sha256 && \
    mv snyk-linux /usr/local/bin/snyk && chmod +x /usr/local/bin/snyk

COPY entrypoints/ /usr/local/bin/entrypoints/
RUN chmod +x /usr/local/bin/entrypoints/*

COPY testrepo/ /go/src/testrepo

ENTRYPOINT ["/usr/local/bin/entrypoints/go.sh"]
